# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5PneZ03u5pUoyMn4L4djLp-ypoLCowc
"""

import streamlit as st
import math

# ---------------- BASE DE DATOS ---------------- #
def cargar_datos():
    return {
        "Carbonato de Litio (Li2CO3)": {
            "Físicas": {
                "Densidad (ρ)": "2.11 g/cm³",
                "PM": "73.89 g/mol",
                "Estado": "Sólido",
                "Color": "Blanco",
                "Llama": "Rojo Carmín",
                "Fusión": "723 °C",
                "Ebullición": "1310 °C (Descomp.)",
                "Granulometría": "90% < 100 μm",
                "Higroscopicidad": "Baja"
            },
            "Químicas": {
                "Reacción": "Li2CO3(s) ⇌ 2Li+ + CO3^2-",
                "Kps": "8.15e-4",
                "Pitzer_beta0": 0.149,
                "Pitzer_beta1": 1.340,
                "Precipita": "Sí (Caliente)",
                "Error modelo ideal": "20-30%"
            },
            "Térmicas": {
                "Cp": "1.34 J/g·K",
                "ΔH_dis": "-12.8 kJ/mol",
                "Conductividad térmica": "0.85 W/m·K"
            },
            "Transporte": {
                "Difusividad": "1.02e-9 m²/s",
                "Movilidad iónica": "4.01e-8 m²/V·s"
            }
        },

        "Cloruro de Litio (LiCl)": {
            "Físicas": {
                "Densidad (ρ)": "2.07 g/cm³",
                "PM": "42.39 g/mol",
                "Estado": "Sólido",
                "Color": "Blanco",
                "Llama": "Rojo Carmín",
                "Higroscopicidad": "Extrema"
            },
            "Químicas": {
                "Reacción": "LiCl → Li+ + Cl-",
                "Kps": "Muy alto",
                "Pitzer_beta0": 0.1494,
                "Pitzer_beta1": 0.3074,
                "Precipita": "No",
                "Error modelo ideal": "45-60%"
            },
            "Térmicas": {
                "Cp": "1.18 J/g·K",
                "ΔH_dis": "-37.0 kJ/mol"
            },
            "Transporte": {
                "Difusividad": "1.35e-9 m²/s"
            }
        }
    }

# ---------------- FUNCIÓN PITZER ---------------- #
def calcular_gamma(b0, b1, I):
    return math.exp(
        -0.51 * (math.sqrt(I) / (1 + 1.2 * math.sqrt(I)))
        + I * b0
        + I * b1
    )

# ---------------- CONFIG APP ---------------- #
st.set_page_config(
    page_title="Base de Datos Litio",
    layout="wide"
)

st.title("🧪 Sistema Experto de Procesamiento de Litio")
st.markdown("Aplicación para análisis de propiedades y coeficientes de actividad (modelo de Pitzer).")

# ---------------- INTERFAZ ---------------- #
compuestos = cargar_datos()

compuesto = st.selectbox(
    "Seleccioná un compuesto:",
    list(compuestos.keys())
)

I = st.slider(
    "Fuerza iónica (I)",
    min_value=0.0,
    max_value=10.0,
    value=1.0
)

datos = compuestos[compuesto]

# ---------------- CÁLCULO ---------------- #
b0 = datos["Químicas"].get("Pitzer_beta0", 0)
b1 = datos["Químicas"].get("Pitzer_beta1", 0)

gamma = calcular_gamma(b0, b1, I)

# ---------------- RESULTADOS ---------------- #
st.subheader(f"📊 Resultados para: {compuesto}")
st.metric("Coeficiente de actividad (γ)", f"{gamma:.4f}")

# ---------------- VISUALIZACIÓN ---------------- #
secciones = ["Físicas", "Químicas", "Térmicas", "Transporte"]
tabs = st.tabs(secciones)

for tab, seccion in zip(tabs, secciones):
    with tab:
        for propiedad, valor in datos[seccion].items():
            st.write(f"**{propiedad}:** {valor}")
